version : "3"
services:
  client:
    image: jshika/frontend
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    
  api:
    image: jshika/backend
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
