---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Run docker-compose
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: pull the images mentioned in docker-compose 
      command: docker-compose -f ./docker-compose.yml pull
    